# File: .github/workflows/pylint.yml

name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"] # Using one recent version is usually enough for linting

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4 # Use the latest version of the action
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install System Dependencies (FFmpeg)
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Analysing the code with Pylint
      # Run pylint on your source directory. It will automatically find the .pylintrc file.
      run: |
